---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  install:
    crds: Create
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: '1.7.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: helm
      interval: 1m
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    installCRDs: true
    startupapicheck:
      podAnnotations:
        sidecar.istio.io/inject: "false"
