---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  install:
    crds: Create
  interval: 5m
  chart:
    spec:
      chart: base
      version: '>1.0'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: helm
      interval: 1m
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    replicaCount: 1
    global:
      istioNamespace: istio-system
